version: '3.4'

services:
  dbot_debug:
    env_file: 
      - .env
    image: dbot-debug-image
    container_name: dbot_debug
    ports:
      - 5678:5678
      - 8080:8080
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 src/dbot.py "]