version: '3.4'

services:
  dbot:
    env_file: 
      - .env
    image: spinstabilized/dbot:core
    container_name: dbot
    ports:
      - 8080:8080/tcp
    build:
      context: .
      dockerfile: ./Dockerfile
