version: '3.4'

services:
  dbot:
    env_file: 
      - .env
    image: dbot-image
    container_name: dbot
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: ./Dockerfile
